### ISSUE TITLE
Abstract component instance config with `settings.spacelift.workspace_enabled: true` get created as Stacks

### ISSUE THREAD

**Issue by Gowiem** [cloudposse/terraform-spacelift-cloud-infrastructure-automation#120]
## Describe the Bug

The following configuration creates a Spacelift stack if imported into a stack file: 

```yaml
components:
  terraform:
    kms/defaults:
      metadata:
        component: kms-key
        abstract: true
      settings:
        spacelift:
          workspace_enabled: true
      vars:
        deletion_window_in_days: 10
        enable_key_rotation: true
        allowed_principals: []
        allowed_roles: {}
        allowed_permission_sets: {}
```

## Expected Behavior

Since it is tagged as `abstract: true` and atmos won't plan / apply this component instance, I would assume that this Spacelift module would avoid the same and not create a Spacelift Stack. 

## Steps to Reproduce
1. Add the above configuration to catalog file.
2. Import it into a stack file.
3. Run this spacelift automation module
4. See that a `<environment>-<stage>-kms-defaults` stack was created. 

## Screenshots
N/A

## Environment (please complete the following information):

* Spacelift Module version: 0.49.4

## Additional Context

N/A
