### ISSUE TITLE
Incorrect policy by ID can pass plan and fail apply

### ISSUE THREAD

**Issue by nitrocode** [cloudposse/terraform-spacelift-cloud-infrastructure-automation#130]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
Incorrect policy by ID can pass plan and fail apply

```yaml
components:
  terraform:
    spacelift/defaults:
      metadata:
        type: abstract
        component: spacelift
      settings:
        spacelift:
          workspace_enabled: true
          policies_by_id_enabled:
            # doesn't exist
            - git-push-administrative-policy
```

https://github.com/cloudposse/terraform-spacelift-cloud-infrastructure-automation/blob/224a1bd794415f7de0a7d3d488a771eebea190b4/modules/stack/main.tf#L165-L172

## Expected Behavior
Either (1) the `spacelift_policy_attachment` resource is smart enough to look before attaching by ID or (2) we use a data source to verify the policy IDs during plan time. I think the latter is the best approach.

It would be nice to grab ALL the stack policy ids, if they exist, and sort, and distinct() them, validate they all exist using a data source during plan. This will then fail fast instead of the fail appearing after a PR merge.

## Additional Context
May be a non-issue if moving to the modern approach using `autoattach` labels https://github.com/cloudposse/terraform-spacelift-cloud-infrastructure-automation/issues/90
