### ISSUE TITLE
Explicitly exclude admin stack from managing child component

### ISSUE THREAD

**Issue by nitrocode** [cloudposse/terraform-spacelift-cloud-infrastructure-automation#138]
### Describe the Feature

I’d like to create a new admin stack which manages the select components in the root space using a tag_filter (which is possible as of now) AND get infrastructure admin stack to EXCLUDE those spacelift-* components explicitly (not possible right now).
I’m thinking, we need either

1. negative tag filters and negative context filters in the vars of the infrastructure
1. or explicit admin stack management OR exclusion in the settings of the components
1. or both ?

### Expected Behavior

Able to explicitly set the admin stack to manage the component OR add an exclusionary filter

### Use Case

See above

### Describe Ideal Solution

An example of (1)

```
components:
  terraform:
    # this should ONLY manage "admin_stack: true" stacks
    spacelift-root:
      metadata:
        component: spacelift
        inherits:
          - spacelift/defaults
      vars:
        tag_filters:
          admin_stack: true

    # this should get ALL stacks in "auto" that do NOT have a tag of "admin_stack: true"
    infrastructure-auto:
      metadata:
        component: spacelift
        inherits:
          - spacelift/defaults
      vars:
        negative_tag_filter:
          admin_stack: true
        context_filters:
          stages:
            - auto

    # this should be ONLY managed by spacelift-root admin stack since it matches
    # the "admin_stack: true"
    spacelift-policy:
      vars:
        tags:
           admin_stack: true
```

An example of (2) would be

```yaml
    spacelift-policy:
      settings:
        spacelift:
          managed_by: spacelift-root
          # or
          # not_managed_by: infrastructure-auto
      vars:
        tags:
           admin_stack: true
```
