### ISSUE TITLE
Merging `setttings.spacelift.labels` / other fields

### ISSUE THREAD

**Issue by Gowiem** [cloudposse/terraform-spacelift-cloud-infrastructure-automation#87]
## Describe the Feature

Merging imported Map and Array fields instead of them being overridden. 

## Expected Behavior

When I have the following two files: 

```yaml
# #1 -- catalog/stage-globals.yaml

terraform:
	components:
		example:
			settings:
				spacelift:
					labels:
						- testing
```

```yaml
# #2 -- stage-internal.yaml

imports:
	- catalog/stage-globals

terraform:
	components:
		example:
			settings:
				spacelift:
					labels:
						- example
```

They result in the following: 

```yaml
# Result as terraform-spacelift-cloud-infrastructure-automation will see it.

terraform:
	components:
		example:
			settings:
				spacelift:
					labels:
						- testing
						- example
```

## Use Case

When importing a catalog of generic config that includes `settings.spacelift.labels` for a component, the importing Stack's component labels take precedence and the imported labels are lost. This makes sense as the Stack config is preferring that it's an "override" mechanic instead of "merge" mechanic, which I'm sure is what we want in the majority of cases. But there are cases such as `labels` where it can make sense to merge the imported values into the overridden values as this allows DRYer configuration. 

## Describe Ideal Solution

Ideas: 

1. A flag in the catalog file that enables merging > overriding for Maps + Arrays
2. A field in the catalog file that specifies which fields should be merged instead of overridden
3. A flag at the TF module layer to enable merging?
3. Plenty of other uglier ways to save it... e.g. `labelAdditions` and similar which wouldn't be sustainable. 

## Alternatives Considered

Dropping this idea altogether 😅 

## Additional Context

This is obviously tricky and may be trying too hard in regards to making Atmos YAML configs smart... but figured I should at least bring the idea up for discussion. Happy if the resolution is "Hey, we don't think that's a good idea, let's shelve it."

**Comment by Gowiem** [comment]
@nitrocode the main example I have was that I was trying to have one of my catalogs specify a label for all stage Stack components. But in some of my stage Stack components I would also need to add another label and that would nullify the imported catalog label that should be applied to all components. For example -- 


```yaml
# #1 -- catalog/stage-globals.yaml

terraform:
  components:
    example:
      settings:
        spacelift:
          labels:
            - helloworld

    other:
      settings:
        spacelift:
          labels:
            - helloworld
```

```yaml
# #2 -- stage-internal.yaml

imports:
  - catalog/stage-globals

terraform:
  components:
    example:
      settings:
        spacelift:
          labels:
            - anotherlabel
      vars: {}

    other:
      vars: {}
```

In the above, my `other` component will get the `helloworld` label, but my `example` component will not because it overrides labels and they're not merged. 

This should definitely be low priority, because I have now refactored my client's Spacelift policy so they no longer need the shared label (i.e. `helloworld` above), BUT I could still see it being relevant. 

Regarding your solution of `labelsAsMap` -- It's a bit funky of a solution (very similar to my suggestions above), but that would do the trick. I think a flag at the component's spacelift settings level that opted in that config's `labels` to get merged (e.g. `concatLabels: true`) would be the nicest, but after refactoring this problem away... I wonder if it is worth the trouble 😅
