### ISSUE TITLE
Support stack environment variables

### ISSUE THREAD

**Issue by nitrocode** [cloudposse/terraform-spacelift-cloud-infrastructure-automation#96]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

https://registry.terraform.io/providers/spacelift-io/spacelift/latest/docs/resources/environment_variable

```hcl
# For a stack
resource "spacelift_environment_variable" "core-kubeconfig" {
  stack_id   = "k8s-core"
  name       = "KUBECONFIG"
  value      = "/project/spacelift/kubeconfig"
  write_only = false
}
```

It would be nice to be able to add env variables on the fly using atmos for spacelift using this module

```yaml
components:
  terraform:
    xyz:
      settings:
        spacelift:
          workspace_enabled:
            environment_variables:
              ATMOS_BASE_PATH: /mnt/workspace/source/terraform/.terraform/modules/monorepo
```
